### ISSUE TITLE
Not working on Vue 2

### ISSUE THREAD

**Issue by EvandroLucas** [MuTsunTsai/clickout-event#3]
I've tried with both `@clickout `and `v-on:clickout`, but neither of those worked for me. 

My element is a div inside a simple table row, with `position-absolute` as a style atribute. `click `events work normally, but the `clickout `ones are not being thrown at all. 

The only thing I did was add the npm package to my project, so I'm not sure if it's enough to make it work.

**Comment by MuTsunTsai** [comment]
Did you add the `<script>` tag or use `require` to import it? Just by installing the NPM package certainly would not make it work.

If you have already done so, I might need to take a look at your repo to see what exactly went wrong.

**Comment by EvandroLucas** [comment]
Well, no, but I found a solution that worked, which is weird since it was just a guess of mine... But anyway, I added those two lines to  my `main.js` file, and it worked like a charm! 

```js
import clickoutEvent from 'clickout-event'
Vue.use(clickoutEvent)
```

**Comment by EvandroLucas** [comment]
I'm not sure if it's intended or not... I found your plugin trough one of your answers in a SO thread, and you've said at the time that there wasn't any support for importing it with `import`, but I just tried to import it the same way we import other packages, and it's working just as promised. 

Maybe this method should be included in the README file for future Vue users to see, shoudn't it?

**Comment by MuTsunTsai** [comment]
In that case I'm guessing you might need just one line:
```
import 'clickout-event';
```
Since it is a fact that Clickout-Event does not really export anything. So in your code `clickoutEvent` will be `undefined` and the next line (`Vue.use`) won't really do anything. Can you comfirm this? In either case I will update README afterwards.

**Comment by EvandroLucas** [comment]
Yup, that worked as well! Thank you!
